# Minimal custom theme - no default Jekyll theme
title: "Pardim93 "
description: "My blog for Articles and Projects"
author: "Wellington Pardim"
url: "https://pardim93.github.io"
baseurl: ""

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge

# SEO / Social
social:
  name: Wellington Pardim
  links:
    - https://github.com/Pardim93

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
